{% set name = "radicli" %}
{% set version = "0.0.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/radicli-{{ version }}.tar.gz
  sha256: 71b1917ab0f1c565e1ae9a830dff0061dab205de093f1329721935c239b8fe7a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - radicli
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/explosion/radicli
  summary: Radically lightweight command-line interfaces
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
